/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huda
 */
public class pnlBooksShow extends javax.swing.JPanel {

    /**
     * Creates new form pnlBooksShow
     */
    public pnlBooksShow() {
        initComponents();
        txtSearch.requestFocus();

        RezervasyonlarGetir();
        backGroundColor();
    }

    Db db = new Db("oteldenemeleri", "root", "");
    LoggerClass lg = new LoggerClass();
    ArrayList<String> bid = new ArrayList<>();

    public void backGroundColor() {
        this.setBackground(new Color(119, 119, 119));
        pnlList.setBackground(new Color(119, 119, 119));
        dcFirst.setBackground(new Color(160, 160, 160));
        dcSecond.setBackground(new Color(160, 160, 160));
        txtSearch.setBackground(new Color(160, 160, 160));
        btnSearch.setBackground(new Color(75, 75, 75));
        tblList.setBackground(new Color(160, 160, 160));

    }

    private void RezervasyonlarGetir() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Oda Numarası");
        dtm.addColumn("Telefon Numarası");
        dtm.addColumn("Başlangıç Tarihi");
        dtm.addColumn("Bitiş Tarihi");
        try {
            bid.clear();
            ResultSet rs = db.connect().executeQuery("call bookingsSearchPro('','','');");
            while (rs.next()) {
                bid.add(rs.getString("" + enums.bookingEnum.booking_id));
                dtm.addRow(new String[]{rs.getString("" + enums.bookingEnum.room_id), rs.getString("" + enums.bookingEnum.phone_number), rs.getString("" + enums.bookingEnum.start_date), rs.getString("" + enums.bookingEnum.due_date)});
            }
            tblList.setModel(dtm);

        } catch (SQLException ex) {
            lg.loggerFunction(ex);
//            System.err.println("fatura getirme hatasi " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlList = new javax.swing.JPanel();
        dcFirst = new com.toedter.calendar.JDateChooser();
        dcSecond = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        pnlBooks = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();

        pnlList.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervasyon Listesi"));

        dcFirst.setDateFormatString("yyyy-MM-dd hh:mm");

        dcSecond.setDateFormatString("yyyy-MM-dd hh:mm");

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Tarih Seçiniz");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setForeground(new java.awt.Color(51, 51, 51));
        txtSearch.setText("Ara...");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });

        pnlBooks.setBorder(javax.swing.BorderFactory.createTitledBorder("Rezervasyonlar"));

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblList);

        javax.swing.GroupLayout pnlBooksLayout = new javax.swing.GroupLayout(pnlBooks);
        pnlBooks.setLayout(pnlBooksLayout);
        pnlBooksLayout.setHorizontalGroup(
            pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );
        pnlBooksLayout.setVerticalGroup(
            pnlBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlListLayout.createSequentialGroup()
                        .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlListLayout.createSequentialGroup()
                                    .addComponent(dcFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlListLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Oda Numarası");
        dtm.addColumn("Telefon Numarası");
        dtm.addColumn("Başlangıç Tarihi");
        dtm.addColumn("Bitiş Tarihi");
        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm");
            String gt = "", ct = "", ara = "";
            if (dcFirst.getDate() != null && dcSecond.getDate() != null) {
                gt = df.format(dcFirst.getDate());
                ct = df.format(dcSecond.getDate());
            }
            if (!txtSearch.getText().trim().equals("")) {
                ara = txtSearch.getText().trim() + "*";
            }
//            System.out.println(gt + " " + ct + " " + ara);
            PreparedStatement pr = db.preConnect("call bookingsSearchPro(?,?,?);");
            pr.setString(1, gt);
            pr.setString(2, ct);
            pr.setString(3, ara);
            ResultSet rs = pr.executeQuery();
            while (rs.next()) {
                bid.add(rs.getString("" + enums.bookingEnum.booking_id));
                dtm.addRow(new String[]{rs.getString("" + enums.bookingEnum.room_id), rs.getString("" + enums.bookingEnum.phone_number), rs.getString("" + enums.bookingEnum.start_date), rs.getString("" + enums.bookingEnum.due_date)});
            }
            tblList.setModel(dtm);
        } catch (SQLException ex) {
            lg.loggerFunction(ex);
//            System.err.println("rezervasyon arama hatasi " + ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText("");       
        
    }//GEN-LAST:event_txtSearchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser dcFirst;
    private com.toedter.calendar.JDateChooser dcSecond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBooks;
    private javax.swing.JPanel pnlList;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
